[config]
schemaVersion = "0.0.1"

[package]
namespace = ""
description = ""
websiteUrl = ""
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
TeamXiaolan-DawnLib = "0.4.0"

[build]
icon = "./icon.png"
readme = "../README.md"
outdir = "../Packages"

[[build.copy]]
source = "../bin/Release/netstandard2.1/{ModGuid}.dll"
target = "BepInEx/plugins/{Product}/"

[[build.copy]]
source = "../res"
target = "BepInEx/plugins/{Product}/Assets"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[publish]
repository = "https://thunderstore.io"
communities = [ "lethal-company", ]
[publish.categories]
lethal-company = [ "mods", "tools", "libraries", "clientside", "serverside" ]